table Cities
	lineageTag: 8a98aa61-df83-491c-9d19-14ce804ef975

	measure 'Selected City' = SELECTEDVALUE(Cities[City])
		lineageTag: 4ce0d9a7-0a2a-45f5-897b-06a568eed426

	measure 'Selected Country' = SELECTEDVALUE(Cities[Country])
		lineageTag: 7cfce829-eaa2-4bc5-85fc-a4b5a6122c23

	column City
		dataType: string
		lineageTag: 8885d5e3-4eff-4e25-97ce-947d99d9492d
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 690fb0c3-480d-481d-bbeb-bc333580398d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition Cities = m
		mode: import
		source =
				let
				    Source = #table(
				        {"City", "Country"},
				        {}
				    ),
				
				    #"Changed Type" = Table.TransformColumnTypes(
				        Source,
				        {{"City", type text}, {"Country", type text}}
				    ),
				
				    #"Add Cities" = Table.InsertRows(
				        #"Changed Type",
				        Table.RowCount(#"Changed Type"),
				        {
				            // UK
				            [City = "London", Country = "United Kingdom"],
				            [City = "Edinburgh", Country = "United Kingdom"],
				            [City = "Birmingham", Country = "United Kingdom"],
				
				            // France
				            [City = "Lyon", Country = "France"],
				            [City = "Marseille", Country = "France"],
				
				            // Japan
				            [City = "Osaka", Country = "Japan"],
				            [City = "Kyoto", Country = "Japan"],
				
				            // USA
				            [City = "New York", Country = "United States of America"],
				            [City = "Miami", Country = "United States of America"],
				            [City = "Los Angeles", Country = "United States of America"],
				
				            // Brazil
				            [City = "Sao Paulo", Country = "Brazil"],
				            [City = "Rio", Country = "Brazil"],
				            [City = "Florianopolis", Country = "Brazil"],
				            [City = "Ubatuba", Country = "Brazil"],
				            [City = "Salvador", Country = "Brazil"],
				
				            // Australia
				            [City = "Melbourne", Country = "Australia"],
				            [City = "Sydney", Country = "Australia"],
				            [City = "Brisbane", Country = "Australia"],
				            [City = "Adelaide", Country = "Australia"],
				
				            // Hong Kong
				            [City = "Hong Kong", Country = "China"],
				
				            // United Arab Emirates
				            [City = "Abu Dhabi", Country = "United Arab Emirates"],
				            [City = "Dubai", Country = "United Arab Emirates"],
				
				            // Thailand
				            [City = "Bangkok", Country = "Thailand"],
				            [City = "Pattaya", Country = "Thailand"],
				
				            // Egypt
				            [City = "Cairo", Country = "Egypt"],
				            [City = "Hurghada", Country = "Egypt"],
				
				            // South Africa
				            [City = "Cape Town", Country = "South Africa"],
				            [City = "Johannesburg", Country = "South Africa"],
				
				            // India
				            [City = "Bangalore", Country = "India"],
				            [City = "Mumbai", Country = "India"],
				            [City = "Delhi", Country = "India"]
				        }
				    ),
				
				    #"Added Custom" = Table.AddColumn(
				        #"Add Cities",
				        "Currency",
				        each
				            if [Country] = "India" then "INR"
				            else if [Country] = "Australia" then "AUD"
				            else if [Country] = "Brazil" then "BRL"
				            else if [Country] = "China" then "CNY"
				            else if [Country] = "Egypt" then "EGP"
				            else if [Country] = "France" then "EUR"
				            else if [Country] = "Japan" then "JPY"
				            else if [Country] = "South Africa" then "ZAR"
				            else if [Country] = "Thailand" then "THB"
				            else if [Country] = "United Arab Emirates" then "AED"
				            else if [Country] = "United Kingdom" then "GBP"
				            else if [Country] = "United States of America" then "USD"
				            else null
				        ),
				
				    #"Merged Queries" = Table.NestedJoin(
				        #"Added Custom",
				        {"Currency"},
				        #"Currency Converter",
				        {"Currency"},
				        "Currency Convertor",
				        JoinKind.LeftOuter
				    ),
				
				    #"Expanded Currency Convertor" = Table.ExpandTableColumn(
				        #"Merged Queries",
				        "Currency Convertor",
				        {"Currency"},
				        {"Currency.1"}
				    ),
				
				    #"Removed Columns" = Table.RemoveColumns(
				        #"Expanded Currency Convertor",
				        {"Currency"}
				    ),
				
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Removed Columns",
				        {{"Currency.1", "Currency"}}
				    ),
				
				    #"Removed Columns1" = Table.RemoveColumns(
				        #"Renamed Columns",
				        {"Currency"}
				    )
				
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

